# Enable "asprunner" by default
default:
  tags:
    - asprunner

update-github:
  only:
    - github_main
  image: hub.cc-asp.fraunhofer.de/mtl-torch/mtl-torch-base:main
  script:
    - ls -a
    - echo asdf
    - git status
    - git fetch --all
    - git checkout github_main
    - git pull --rebase
    - git status
    # Set git config to Gitlab user
    - git config --global user.email $GITLAB_USER_EMAIL
    - git config --global user.name $CI_COMMIT_AUTHOR
    # Try to resolve unexpected state
    # - git pull https://${testghtoken}@github.com/Telcrome/mirrortestpublic.git main --rebase
    # - git push
    - git push https://${testghtoken}@github.com/Telcrome/mirrortestpublic.git github_main:main
