# Enable "asprunner" by default
default:
  tags:
    - asprunner

update-github:
  only:
    - github_main
  image: hub.cc-asp.fraunhofer.de/mtl-torch/mtl-torch-base:main
  script:
    - ls -a
    - echo asdf
    - git status
    - git checkout github_main
    - git status
    - git push https://${testghtoken}@github.com/Telcrome/mirrortestpublic.git github_main:main
