name: Sync to Gitlab

run-name: ${{ github.actor }} is pushing changes to Gitlab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: self-hosted
    # runs-on: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "Hello, world!"
      - run: ls /data
      # - name: Add Gitlab remote
      #   run: git remote add gitlab
      - name: Push to Gitlab
        run: git push git@gitlab.cc-asp.fraunhofer.de:jschaefer/mirrortest.git main:github_main
        env:
          GITLAB_TOKEN: ${{ secrets.GLTOKEN }}
