name: Sync to Gitlab

run-name: ${{ github.actor }} is pushing changes to Gitlab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: [self-hosted, docker://ubuntu:22.04]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Gitlab
        run: git push git@gitlab.cc-asp.fraunhofer.de:jschaefer/mirrortest.git main:github_main
        env:
          GITLAB_TOKEN: ${{ secrets.GLTOKEN }}
